### PR TITLE
More supporting examples for parametricity.

### PR DESCRIPTION
**Pull request by felipeeflores**
A few more examples to make it clearer why types are documentation.

### CODE REVIEW

**Comment by wjlow** [comment]
Are these good examples?

`List[A] => Int` has many many many implementations. You could just return `100` and it would compile. Or is this what you're trying to communicate?

**Comment by felipeeflores** [comment]
Yes, @wjlow the idea is to show that as we make types more specific it is easier to understand what a function does. Will add come comments around that.

**Comment by wjlow** [comment]
Can we leave this in an example you write in the REPL?

So we can keep the exercises lean. We may have to reduce the amount of exercises. But I agree this is an important thing to show.

**Comment by felipeeflores** [comment]
No problem. Will add them as I explain parametricity to my wc.

**Pull request closed without merging**
